[workspace]
authors = ["Luis Pedro Coelho <luis@luispedro.org>"]
channels = ["conda-forge", "bioconda"]
name = "sardyne"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]

[feature.sardyne.dependencies]
python = "3.11.*"
polars = ">=1.22.0,<2"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
requests = ">=2.32.3,<3"
prodigal = ">=2.6.3,<3"
pyrodigal = ">=3.6.3,<4"
ipython = ">=8.32.0,<9"
eggnog-mapper = ">=2.1.3,<3"

[feature.sardyne.pypi-dependencies]
jug = { git = "https://github.com/luispedro/jug.git", rev = "e6d4fcff297a84198ef4fcbbad6bbdf410a38720" }

[feature.checkM2.dependencies]
# checkm2 1.1.0 resulted in an error (25 Feb 2025)
checkm2 = "1.0.1.*"

[environments]
checkm2 = ["checkM2"]
sardyne = ["sardyne"]

